import { forwardRef,useEffect,useRef,useState } from 'react';
import Globe,{type GlobeMethods} from 'react-globe.gl'; import type { TravelPlace } from '../../types/travel';
export interface GlobeHandle { flyTo:(lat:number,lng:number,altitude?:number)=>void; zoom:(delta:number)=>void; reset:()=>void }
interface Props{places:TravelPlace[];autoRotate:boolean;selected?:TravelPlace;onSelect:(p:TravelPlace)=>void;onEarthClick:(lat:number,lng:number)=>void;onInteraction:()=>void}
const marker=(place:TravelPlace)=>{const root=document.createElement('button');root.className=`globe-marker ${place.status}`;root.setAttribute('aria-label',`Open ${place.name}`);root.innerHTML=`<span></span><div class="marker-tip">${place.photos[0]?`<img src="${place.photos[0].url}" alt="">`:''}<b>${place.name}</b><small>${place.country} · ${place.status==='visited'?'Visited':'Bucket list'}</small></div>`;return root};
export const TravelGlobe=forwardRef<GlobeHandle,Props>(function TravelGlobe({places,autoRotate,selected,onSelect,onEarthClick,onInteraction},ref){
 const globe=useRef<GlobeMethods>();const wrap=useRef<HTMLDivElement>(null);const [size,setSize]=useState({w:innerWidth,h:innerHeight});
 useEffect(()=>{const ro=new ResizeObserver(([e])=>setSize({w:e.contentRect.width,h:e.contentRect.height}));if(wrap.current)ro.observe(wrap.current);return()=>ro.disconnect()},[]);
 useEffect(()=>{const controls=globe.current?.controls();if(controls){controls.autoRotate=autoRotate;controls.autoRotateSpeed=.35;controls.enableDamping=true;controls.dampingFactor=.08}},[autoRotate]);
 const api:GlobeHandle={flyTo:(lat,lng,altitude=1.65)=>globe.current?.pointOfView({lat,lng,altitude},1300),zoom:(d)=>{const p=globe.current?.pointOfView();if(p)globe.current?.pointOfView({...p,altitude:Math.max(.7,Math.min(3.5,p.altitude+d))},300)},reset:()=>globe.current?.pointOfView({lat:18,lng:10,altitude:2.25},1000)}; if(typeof ref==='function')ref(api);else if(ref)ref.current=api;
 return <div className="globe-wrap" ref={wrap} onPointerDown={onInteraction}><Globe ref={globe} width={size.w} height={size.h} backgroundColor="rgba(0,0,0,0)" globeImageUrl="https://unpkg.com/three-globe/example/img/earth-blue-marble.jpg" bumpImageUrl="https://unpkg.com/three-globe/example/img/earth-topology.png" atmosphereColor="#58a6ff" atmosphereAltitude={.18} htmlElementsData={places} htmlLat="latitude" htmlLng="longitude" htmlAltitude={.025} htmlElement={d=>marker(d as TravelPlace)} onHtmlElementClick={d=>onSelect(d as TravelPlace)} onGlobeClick={({lat,lng})=>onEarthClick(lat,lng)} htmlElementVisibilityModifier={(el,visible)=>{el.style.opacity=visible?'1':'0';el.style.pointerEvents=visible?'auto':'none'}} />{selected&&<div className="selection-label">Exploring <b>{selected.name}</b></div>}</div>
});
